### ISSUE TITLE
middleware with optional parameters

### ISSUE THREAD

**Issue by rcoelhoAtterbury** [vkarpov15/awaitjs-express#12]
Express documentation shows an example, 
[https://expressjs.com/en/guide/writing-middleware.html](url)
```
module.exports = function (options) {
  return function (req, res, next) {
    // Implement the middleware function based on the options object
    next()
  }
}
The middleware can now be used as shown below.
var mw = require('./my-middleware.js')
app.use(mw({ option1: '1', option2: '2' }))
```

When I tried this with postAsync, the compiler threw an error, saying that a promise was found where a function was expected; it worked if I modified the code and invocation 
`router.postAsync('/', async (req, res, next) => {
    await myAsyncMiddleware(req, res, next, myparameter)
  }, myOperation
);
`
Can the express js recommended model be supported by awaitjs? 
It's a lot cleaner to write
`router.postAsync('/', myAsyncMiddleware(myparameter), myOperation);`
than the longer model above.

**Comment by vkarpov15** [comment]
Should be fine if you do:

```javascript
module.exports = function (options) {
  return async function (req, res, next) {
    // Implement the middleware function based on the options object
    next()
  }
}
The middleware can now be used as shown below.
var mw = require('./my-middleware.js')
app.useAsync(mw({ option1: '1', option2: '2' }))
```

The error message you mentioned (a promise was found where a function was expected) is indicative of you doing something like `module.exports = async function(options) { return function (req, res, next) { ... } }` rather than `module.exports = function(options) { return async function (req, res, next) { ... } }`
