### ISSUE TITLE
potential racecondition?

### ISSUE THREAD

**Issue by japrescott** [vkarpov15/awaitjs-express#22]
First off, thanks for creating another awesome lib @vkarpov15 :)

I am seeing some sort of racecondition but have troubles spotting it reliably why its happening (or if this has nothing to do with awaitjs/express).

Following is an abstraction of what I am doing.
Generally what I want is to have multiple different files, each with a `Router` from `@awaitjs/express` that are then put together like the following;
```typescript
//tags.ts
export const tagsRouter = Router({ mergeParams: true });
tagsRouter.getAsync('/*', async (req, res) => {
	console.log('Tag routes..')
	await new Promise<void>((resolve) => {
		setTimeout(resolve, 5000)
	})
	console.log('Tags finished..')
	next()
})
tagsRouter.getAsync('/*', async (req, res) => {
	const data = await something()
	console.log('Do Tag..')
	res.json(data)
})
// more routes...

//models.ts
export const modelsRouter = Router({ mergeParams: true });
modelsRouter.getAsync('/*', async (req, res) => {
	console.log('Model routes..')
	await new Promise<void>((resolve) => {
		setTimeout(resolve, 5000)
	})
	console.log('Models finished..')
	next()
})
// more routes...

//main.ts
import {tagsRouter} from 'tags'
import {modelsRouter} from 'models'
import {ensureAccess} from '../access';
export const mainRouter = Router({ mergeParams: true });

mainRouter.use(':userId/*', ensureAccess); //some access control which makes a async call to the database
mainRouter.use(':userId/tags', tagsRouter);
mainRouter.use(':userId/models', modelsRouter); 

```

When running this from time to time I get the outputs in a wrong order
```
Tag routes..
Do Tag..
Tags Finished..
```
instead of
```
Tag routes..
Tags Finished..
Do Tag..
```

Am I messing something up in my setup? Am I misunderstanding this library?

**Comment by vkarpov15** [comment]
@japrescott is it possible that you're just hitting the same endpoint twice in parallel?

If you can come up with a standalone script that can reliably demonstrate this issue I'm happy to take a look :+1:

**Comment by japrescott** [comment]
Hey @vkarpov15
I did more debugging and was able to create a reproducible script

```typescript
import { addAsync, Router } from '@awaitjs/express';
import bodyParser from 'body-parser';
import cors from 'cors';
import express, { Request, Response, NextFunction, RequestHandler } from 'express';




async function two() {
	const answer = { answer: 123123 }
	await new Promise<void>((resolve) => setTimeout(resolve, 2000))
	throw new Error('asdasdasd')
}

async function one() {
	return await two()
}

const routerLevel3 = Router({ mergeParams: true });
routerLevel3.getAsync('/', (async (req, res) => {
	
	const result = await one();
	res.json(result)
}) as RequestHandler);

const routerLevel2 = Router({ mergeParams: true });
routerLevel2.use('/level3', routerLevel3)

const routerLevel1 = Router({ mergeParams: true });
routerLevel1.use('/level2', routerLevel2)
routerLevel1.use((err: Error, _req: Request, _res: Response, _next: NextFunction) => {
	console.log('Caught err', err)
})


const app = addAsync(express());
app.use(cors());
app.use(bodyParser.json({ limit: '50mb' }));
app.useAsync((req, res, next) => {
	next()
});
app.use('/', routerLevel1);
app.use((err: Error, req: Request, res: Response, _next: NextFunction) => {
	console.log('Main errorHandler called', err)
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	res.status(500).end(`${(res as unknown as any).sentry || 'error unclear'}\n`);
});

app.listen(4000, () => {
	console.log(`app-api up and running on ${4000}`)
});

```

Expectation when calling  **http://localhost:4000/level2/level3/**

**Comment by EvanSmith-git** [comment]
This is a problem with my pull request, confirmed by installing the previous version and running the code you provided ( `npm i @awaitjs/express@0.7.0` ). It has something to do with the `_once(fn)` function not preventing multiple calls to `next()` anymore, and `next()` getting called more times than it should. Trying to figure this out now.

**Comment by japrescott** [comment]
@EvanSmith-git 
Thank you very much for looking in to this! I installed your branch to test and everything works as expected!

**Comment by 7opf** [comment]
I've also run into this issue and confirm @EvanSmith-git branch fixes it in our tests.

**Comment by japrescott** [comment]
@vkarpov15 do you have a timeline when you plan to publish a new release as 0.7.1 is essentially broken?

**Comment by japrescott** [comment]
thanks @vkarpov15 <3
